"""Public facade for the RAKL mathematical-research reference profile.

The modules behind this facade deliberately separate planning from authority. Path
search and strategy motifs generate candidate research routes; theorem, novelty and
publication stages are still controlled by explicit assurance receipts. Strict RAKL
mathematical discovery additionally requires a frozen context/analogue-transfer
packet and an auditable public research trace before candidate generation.
"""

from .math_context import (
    REQUIRED_PRE_CANDIDATE_ACTIONS,
    AnalogyScanStatus,
    ContextGateReport,
    ContextGateVerdict,
    CrossDomainAnalogy,
    MathContextFiber,
    MethodTransfer,
    audit_math_context_fiber,
)
from .math_research_assurance import (
    AssuranceReport,
    AssuranceVerdict,
    FormalizationWitness,
    MathClaimStage,
    MathResearchRecord,
    NoveltyCertificate,
    ProofReceipt,
    audit_formalization,
    audit_novelty,
    audit_proof_receipt,
    classify_math_record,
    update_novelty_certificate,
)
from .math_research_runtime import (
    MathResearchPlan,
    derive_planning_state,
    plan_math_research,
    publication_ready,
)
from .problem_solving_algebra import (
    DEFAULT_OPERATOR_ATLAS,
    ObstructionKind,
    OperatorFamily,
    PathCandidate,
    ProblemSignature,
    ProblemState,
    ResearchOperator,
    TerminalCertificate,
    TerminalKind,
    apply_operator_symbolic,
    close_with_certificate,
    operator_applicable,
    search_operator_paths,
)
from .proof_dag import (
    ProofDAG,
    ProofDAGReport,
    ProofEdge,
    ProofNode,
    ProofNodeKind,
    ProofNodeStatus,
    ProofRelation,
    add_edge,
    add_node,
    all_dependencies_verified,
    dependency_closure,
    refute_node,
    validate_proof_dag,
    verify_checkpoint,
)
from .research_trace import (
    REQUIRED_PRE_CANDIDATE_EVENTS,
    REQUIRED_TRACE_ACTIONS,
    MathResearchTrace,
    ResearchTraceEntry,
    ResearchTraceEventType,
    ResearchTraceReport,
    TraceGateVerdict,
    audit_pre_candidate_trace,
)
from .strategy_motifs import (
    DEFAULT_STRATEGY_MOTIFS,
    MotifInstantiation,
    StrategyMotif,
    instantiate_strategy_motif,
    rank_strategy_motifs,
    validate_strategy_motif,
)

__all__ = [
    "AnalogyScanStatus",
    "AssuranceReport",
    "AssuranceVerdict",
    "ContextGateReport",
    "ContextGateVerdict",
    "CrossDomainAnalogy",
    "DEFAULT_OPERATOR_ATLAS",
    "DEFAULT_STRATEGY_MOTIFS",
    "FormalizationWitness",
    "MathClaimStage",
    "MathContextFiber",
    "MathResearchPlan",
    "MathResearchRecord",
    "MathResearchTrace",
    "MethodTransfer",
    "MotifInstantiation",
    "NoveltyCertificate",
    "ObstructionKind",
    "OperatorFamily",
    "PathCandidate",
    "ProblemSignature",
    "ProblemState",
    "ProofDAG",
    "ProofDAGReport",
    "ProofEdge",
    "ProofNode",
    "ProofNodeKind",
    "ProofNodeStatus",
    "ProofReceipt",
    "ProofRelation",
    "REQUIRED_PRE_CANDIDATE_ACTIONS",
    "REQUIRED_PRE_CANDIDATE_EVENTS",
    "REQUIRED_TRACE_ACTIONS",
    "ResearchOperator",
    "ResearchTraceEntry",
    "ResearchTraceEventType",
    "ResearchTraceReport",
    "StrategyMotif",
    "TerminalCertificate",
    "TerminalKind",
    "TraceGateVerdict",
    "add_edge",
    "add_node",
    "all_dependencies_verified",
    "apply_operator_symbolic",
    "audit_formalization",
    "audit_math_context_fiber",
    "audit_novelty",
    "audit_pre_candidate_trace",
    "audit_proof_receipt",
    "classify_math_record",
    "close_with_certificate",
    "dependency_closure",
    "derive_planning_state",
    "instantiate_strategy_motif",
    "operator_applicable",
    "plan_math_research",
    "publication_ready",
    "rank_strategy_motifs",
    "refute_node",
    "search_operator_paths",
    "update_novelty_certificate",
    "validate_proof_dag",
    "validate_strategy_motif",
    "verify_checkpoint",
]
